Edpub 1073 implement new email template
eosdis-nasa/earthdata-pub-api pull request #26
Opened 2024-02-20 16:06 UTC by DavisGauntUAH

# Description

Implements new email templates and improves send consistency

## Spec

See Ticket: [EDPUB-1073](https://bugs.earthdata.nasa.gov/browse/EDPUB-1073)

---

## Validation

1. Make sure all merge request checks have passed (CI/CD).
2. Deploy branch to sit.
3. Make sure your account is a data producer and daac staff
4. Run a full workflow to completion and ensure all emails are received.  
5. Add an additional user to a conversation and ensure a DM email is sent.

---

## Change Log

Implements new email templates and improves send consistency

* [Fix _____](link to commitid)

2024-02-21 18:48 UTC, camposeddie commented on src/nodejs/lambda-layers/message-util/src/templates/default-step-promotion.js
> +                    <p><a style="text-align: left;" href="https://pub.earthdata.nasa.gov/dashboard/requests/id/${eventMessage.submission_id}" aria-label="View the request">${eventMessage.submission_n
Should use environment variable for populating URL to avoid hardcoding PROD URL

2024-02-21 18:48 UTC, camposeddie commented on src/nodejs/lambda-layers/message-util/src/templates/default-step-promotion.js
> +                    <p><a style="text-align: left;" href="https://pub.earthdata.nasa.gov/dashboard" aria-label="Visit Earthdata Pub Dashboard">https://pub.earthdata.nasa.gov/dashboard</a></p>
Same as above hardcode comment

2024-02-21 19:43 UTC, camposeddie commented
Automated step `Map Question Response To Ummc` taking significantly longer than previously to complete and update status

2024-02-21 19:45 UTC, camposeddie commented
Action emails like the following being sent to data producer (not relevant):
```
Map Question Response To Ummc is complete, Create Skeleton Dataset Record In Mmt is ready to be worked on. Please click on the green button on the far right of your submission's row to work on this action, if applicable
```

2024-02-21 20:17 UTC, camposeddie requested changes
See PR comments for issues discovered.

2024-02-21 21:26 UTC, DavisGauntUAH commented
> Automated step `Map Question Response To Ummc` taking significantly longer than previously to complete and update status

I think this is a felt artifact of the emails having a delay on being sent of a few seconds each. So even if the auto step barely misses being shown in the dashboard load you will be a fair amount of time before an email is received saying the step is done.

2024-02-21 21:26 UTC, DavisGauntUAH commented
> Returning a submission during the review step is instead progressing to the next step as an review_approved event.
> 
> Update: This is not a result of this PR. The issue seems to be an existing issue on the develop branch

fixed

2024-02-22 16:19 UTC, camposeddie approved these changes

2024-02-22 16:19 UTC, merged