feature: new role for UWG members
eosdis-nasa/earthdata-pub-api pull request #78
Opened 2024-05-17 12:31 UTC by joncarlson

# Description

Adding a role for UWG members, to support the GES DISC task of assigning UWG members to a review

## Spec

Designs: [link to design if applicable; delete if not]

See Ticket: [link to ticket if applicable; delete if not]

---

## Validation

1. Make sure all merge request checks have passed (CI/CD).
2. Pull related branches locally.
3. Navigate to... [continue instructions]

_(For an example of good validation instructions, check out
[Bryan's Bouncy Ball PR](https://github.com/sparkbox/bouncy-ball/pull/56#issue-192153701).)_

---

## Change Log

_(copy/paste-able change log notes. check the box when the change is also in CHANGELOG.md)_

* [Add _____](link to commitid)
* [Fix _____](link to commitid)

2024-05-17 19:18 UTC, DavisGauntUAH requested changes

2024-05-17 19:18 UTC, DavisGauntUAH commented on src/postgres/7-seed.sql
> +INSERT INTO edprole_privilege VALUES ('a5b4947a-67d2-434e-9889-59c2fad39676', 'NOTE_NEW');
Please fix the edprole_id.  They should be `19ac227b-e96c-46fa-a378-cf82c461b669`

2024-05-17 19:18 UTC, DavisGauntUAH commented on src/postgres/9-updates.sql
> +INSERT INTO edprole_privilege VALUES ('a5b4947a-67d2-434e-9889-59c2fad39676', 'NOTE_NEW');
Same as in seed.sql

2024-06-14 14:59 UTC, joncarlson commented on src/postgres/9-updates.sql
> +INSERT INTO edprole_privilege VALUES ('a5b4947a-67d2-434e-9889-59c2fad39676', 'NOTE_NEW');
Changes made

2024-06-20 19:18 UTC, camposeddie commented
@joncarlson @DavisGauntUAH Have the requested changes of this PR been resolved? Is this PR ready to be validated for merging?

2024-06-20 19:57 UTC, joncarlson commented
@camposeddie Yes, I've made the requested changes

2024-06-21 17:20 UTC, camposeddie approved these changes

2024-06-21 17:25 UTC, camposeddie commented
Everything looks good with the assumption that https://github.com/eosdis-nasa/earthdata-pub-dashboard/pull/50 or similar follow on tasks adds functionality so that UWG member is added as a contributor when assigned to review a request. Otherwise, the UWG role doesn't have any visibility into requests.

2024-06-21 17:28 UTC, merged